name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: temurin

      - name: Install npm dependencies
        run: |
          npm install && npx expo prebuild --platform android
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/casdoorapp.apk
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: casdoorapp.apk
          path: android/app/build/outputs/apk/release/

  build-ipa:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: temurin

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install && npx expo prebuild --platform ios

      - name: Pod Install
        run: cd ios && rm Podfile.lock && pod install --repo-update

      - name: build
        run: cd ios && xcodebuild -scheme casdoorapp -workspace casdoorapp.xcworkspace -configuration Release clean archive -archivePath "build/casdoorapp.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: archive to ipa
        run: |
          cd ios
          mkdir build/Payload
          mv build/casdoorapp.xcarchive/Products/Applications/casdoorapp.app build/Payload/casdoorapp.app
          cd build
          zip -r casdoorapp.ipa Payload/
      - name: Update artifact
        uses: actions/upload-artifact@v4
        with:
            name: casdoorapp.ipa
            path: ios/build/casdoorapp.ipa

  semantic-release:
    needs: [build-ipa, build-apk]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Download iOS build artifacts
        uses: actions/download-artifact@v4
        with:
          name: casdoorapp.ipa
          path: release/ios/

      - name: Download Android build artifacts
        uses: actions/download-artifact@v4
        with:
          name: casdoorapp.apk
          path: release/android/

      - name: Run semantic-release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
